version: "3.8"
services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: muni_test
    ports:
      - "5432:5432"
    volumes:
      - ./posgres_data:/var/lib/postgresql/data
  pgadmin:
    container_name: "pgadmin_container"
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: test
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadminfr